"""
Fixed (non-AI) part of the Streamlit website: the app entry point and page navigation,
the theme, the contact-form storage (data/contacts.csv) and the site test script.

The agents only write the header/footer and the page files; everything that must always
work is generated here from the spec.
"""
import json
import re

from models import SiteSpec
from themes import THEMES

RESERVED_COMPONENTS = {"App", "Layout", "Contact"}


def normalize_spec(spec: SiteSpec) -> SiteSpec:
    """Make page names, routes and field names safe to use in generated code."""
    seen = set()
    for page in spec.pages:
        words = re.sub(r"[^A-Za-z0-9]", " ", page.component or page.name).split()
        name = "".join(w[0].upper() + w[1:] for w in words)   # keeps 'AboutUs' as is
        if not name or not name[0].isalpha():
            name = "Page" + name
        if name in RESERVED_COMPONENTS:
            name += "Page"
        while name in seen:
            name += "X"
        seen.add(name)
        page.component = name
        route = page.route.strip().strip("/").lower().replace(" ", "-")
        page.route = "/" + re.sub(r"[^a-z0-9-]", "", route)
    if spec.pages and not any(p.route == "/" for p in spec.pages):
        spec.pages[0].route = "/"
    spec.pages.sort(key=lambda p: p.route != "/")   # home page first
    spec.contact.route = "/contact"
    for f in spec.contact.fields:
        f.name = re.sub(r"[^a-z0-9]+", "_", f.name.lower()).strip("_") or "field"
    return spec


def allowed_paths(spec: SiteSpec):
    """Files the Developer agent is allowed to write."""
    return {"components/layout.py", spec.contact.file} | {p.file for p in spec.pages}


# ------------------------------------------------------------------ generated files
def app_py(spec: SiteSpec) -> str:
    pages = [
        f'    st.Page("{p.file}", title="{p.name}", default=True),' if p.route == "/" else
        f'    st.Page("{p.file}", title="{p.name}", url_path="{p.url_path}"),'
        for p in spec.pages
    ]
    pages.append(f'    st.Page("{spec.contact.file}", title="{spec.contact.name}", '
                 f'url_path="{spec.contact.url_path}"),')
    pages_code = "\n".join(pages)
    return f'''"""
{spec.site_name} - Streamlit website entry point.
Generated by scaffold.py. Run it with:  streamlit run app.py
"""
import streamlit as st

from components.layout import render_footer, render_header
from lib.theme import inject_css

st.set_page_config(page_title="{spec.site_name}", page_icon="✨", layout="wide",
                   initial_sidebar_state="collapsed")
inject_css()

PAGES = [
{pages_code}
]

page = st.navigation(PAGES, position="hidden")   # navigation is done by the header links
render_header()
page.run()
render_footer()
'''


def theme_py(theme_id: str) -> str:
    theme = THEMES[theme_id]
    c = theme["colors"]
    fonts = "&".join("family=" + f.replace(" ", "+") + ":wght@400;600;700"
                     for f in dict.fromkeys(theme["fonts"].values()))
    return f'''"""
Theme "{theme_id}" chosen by the Theme Decision Maker agent. Generated by scaffold.py.
Colours are also set in .streamlit/config.toml; this file adds fonts and CSS classes.
"""
import streamlit as st

THEME_ID = "{theme_id}"
COLORS = {json.dumps(c, indent=4)}

CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?{fonts}&display=swap');
h1, h2, h3, h4 {{ font-family: '{theme["fonts"]["heading"]}', sans-serif !important; }}

/* Header and footer bars: st.container(key="site_header") / st.container(key="site_footer") */
.st-key-site_header, .st-key-site_footer {{
    background: {c["header-bg"]}; color: {c["header-text"]};
    padding: 14px 24px; border-radius: {theme["radius"]};
}}
.st-key-site_footer {{ margin-top: 48px; padding: 28px 24px; }}
.st-key-site_header p, .st-key-site_header span, .st-key-site_header a,
.st-key-site_footer p, .st-key-site_footer span, .st-key-site_footer a,
.st-key-site_footer li {{ color: {c["header-text"]} !important; }}
/* captions and .muted text must stay readable on the dark bars */
.st-key-site_header [data-testid="stCaptionContainer"], .st-key-site_footer [data-testid="stCaptionContainer"],
.st-key-site_header .muted, .st-key-site_footer .muted {{ color: {c["header-text"]} !important; opacity: 0.8; }}
.st-key-site_header .badge, .st-key-site_footer .badge {{ color: {c["text"]} !important; }}
.st-key-site_header a:hover, .st-key-site_footer a:hover {{ background: rgba(255,255,255,0.12); }}

/* Highlighted call-to-action link: st.container(key="header_cta") */
.st-key-header_cta a {{
    background: {c["primary"]}; border-radius: {theme["radius"]}; justify-content: center;
}}
.st-key-header_cta a p, .st-key-header_cta a span {{ color: {c["primary-contrast"]} !important; font-weight: 700; }}

/* HTML helpers for st.markdown(..., unsafe_allow_html=True) */
.hero {{
    background: linear-gradient(135deg, {c["primary"]}, {c["secondary"]});
    color: {c["primary-contrast"]}; padding: 56px 32px; border-radius: {theme["radius"]};
    text-align: center; margin-bottom: 24px;
}}
.hero h1, .hero h2, .hero p {{ color: {c["primary-contrast"]} !important; }}
.card {{
    background: {c["surface"]}; border: 1px solid {c["border"]}; border-radius: {theme["radius"]};
    padding: 20px; height: 100%;
}}
.muted {{ color: {c["muted"]}; }}
.badge {{
    display: inline-block; padding: 2px 10px; border-radius: 999px;
    background: {c["border"]}; color: {c["text"]}; font-size: 0.85rem; margin-right: 6px;
}}
</style>
"""


def inject_css():
    st.markdown(CSS, unsafe_allow_html=True)
'''


def config_toml(theme_id: str) -> str:
    theme = THEMES[theme_id]
    c = theme["colors"]
    return f'''# Generated by scaffold.py - theme "{theme_id}" chosen by the Theme Decision Maker agent
[theme]
base = "{theme["mode"]}"
primaryColor = "{c["primary"]}"
backgroundColor = "{c["bg"]}"
secondaryBackgroundColor = "{c["border"]}"
textColor = "{c["text"]}"
font = "{theme["fonts"]["body"]}, sans-serif"
headingFont = "{theme["fonts"]["heading"]}, sans-serif"
baseRadius = "{theme["radius"]}"

[client]
toolbarMode = "minimal"

[server]
showEmailPrompt = false

[browser]
gatherUsageStats = false
'''


STORAGE_PY = '''"""
Contact form storage: validates a submission and appends it to data/contacts.csv.
Generated by scaffold.py (not by AI) so saving submissions always works.
"""
import csv
import json
import os
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = json.loads((ROOT / "site_config.json").read_text(encoding="utf-8"))
CONTACT_FIELDS = CONFIG["contact_fields"]      # list of {name, label, type, required, options}
EMAIL_RE = re.compile(r"^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")


def csv_path() -> Path:
    return ROOT / os.environ.get("CONTACTS_CSV", "data/contacts.csv")


def validate(values: dict) -> str | None:
    """Return an error message, or None if the submission is valid."""
    for field in CONTACT_FIELDS:
        value = str(values.get(field["name"]) or "").strip()
        if field["required"] and not value:
            return f"{field['label']} is required."
        if value and field["type"] == "email" and not EMAIL_RE.match(value):
            return f"{field['label']} is not a valid email address."
        if value and field["type"] == "select" and field["options"] and value not in field["options"]:
            return f"Please choose a valid option for {field['label']}."
    return None


def _cell(value) -> str:
    text = str(value or "").replace("\\r", " ").replace("\\n", " ").strip()
    return "'" + text if text[:1] in ("=", "+", "-", "@") else text   # block spreadsheet formulas


def save_contact(values: dict) -> str | None:
    """Validate and save one submission. Returns an error message, or None when saved."""
    error = validate(values)
    if error:
        return error
    path = csv_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    is_new = not path.exists()
    with path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        if is_new:
            writer.writerow(["submitted_at"] + [field["name"] for field in CONTACT_FIELDS])
        writer.writerow([datetime.now().isoformat(timespec="seconds")]
                        + [_cell(values.get(field["name"])) for field in CONTACT_FIELDS])
    return None
'''


CHECK_SITE_PY = r'''"""
Automated site tests (generated by scaffold.py). Uses Streamlit's AppTest to run the app
without a browser.

    python tests/check_site.py render    # render every page, list its links, headings and text
    python tests/check_site.py contact   # fill in and submit the Contact Us form

Prints one line "RESULTS <json>".
"""
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
os.chdir(ROOT)
sys.path.insert(0, str(ROOT))
os.environ.setdefault("CONTACTS_CSV", "data/contacts.test.csv")

from streamlit.testing.v1 import AppTest  # noqa: E402

CONFIG = json.loads((ROOT / "site_config.json").read_text(encoding="utf-8"))
TAG = re.compile(r"<[^>]+>")


def open_page(file=None):
    """Run app.py (header + home page + footer), or with `file` run only that page script."""
    at = AppTest.from_file(str(ROOT / "app.py"), default_timeout=60).run()
    if file:
        at.switch_page(file).run()
    return at


def walk(node):
    yield node
    for child in getattr(node, "children", {}).values():
        yield from walk(child)


def describe(at):
    """Collect headings, text and page links from the rendered page."""
    headings, texts, links = [], [], []
    for el in walk(at.main):
        kind = getattr(el, "type", "")
        if kind in ("title", "header", "subheader"):
            headings.append(el.value)
        elif kind in ("markdown", "caption", "text", "success", "info", "warning", "error"):
            value = str(el.value)
            if "<style>" in value:
                continue
            headings += [TAG.sub("", h).strip() for h in re.findall(r"<h[1-4][^>]*>(.*?)</h[1-4]>", value, re.S)]
            headings += [line.lstrip("# ").strip() for line in value.splitlines() if re.match(r"^#{1,4} ", line)]
            text = re.sub(r"\s+", " ", TAG.sub(" ", value)).strip()
            if text:
                texts.append(text)
        elif kind == "page_link":
            links.append({"label": el.proto.label, "url_path": el.proto.page})
            texts.append(f"[link: {el.proto.label} -> /{el.proto.page}]")
        elif kind == "button":
            texts.append(f"[button: {el.label}]")
        elif kind in ("text_input", "text_area", "selectbox"):
            options = f" options={list(el.options)}" if kind == "selectbox" else ""
            texts.append(f"[form field {kind}: '{el.label}' key={el.key}{options}]")
    return headings, texts, links


def render():
    """Header/footer come from app.py (same on every page); page content from each page file."""
    results = {"layout": None, "pages": []}
    for page in [None] + CONFIG["pages"] + [CONFIG["contact"]]:
        try:
            at = open_page(page and page["file"])
            errors = [str(e.value) for e in at.exception]
            headings, texts, links = describe(at)
            item = {"ok": not errors, "error": "\n".join(errors)[:1500],
                    "headings": headings, "texts": texts, "links": links}
        except Exception as e:  # noqa: BLE001
            item = {"ok": False, "error": f"{type(e).__name__}: {e}"[:1500], "headings": [], "texts": [], "links": []}
        if page is None:
            results["layout"] = item
        else:
            results["pages"].append({"file": page["file"], **item})
    # header/footer text = text of the full app.py run that is not part of the home page itself
    home = results["pages"][0] if results["pages"] else {"texts": [], "links": []}
    results["layout"]["texts"] = [t for t in results["layout"]["texts"] if t not in home["texts"]]
    for link in home["links"]:   # links on the home page itself are not header/footer links
        if link in results["layout"]["links"]:
            results["layout"]["links"].remove(link)
    return results


def sample(field):
    return {"email": "test.user@example.com", "tel": "9876543210",
            "select": field["options"][0] if field["options"] else "Test option",
            "textarea": "Automated test message, with a comma."}.get(field["type"], "Test " + field["label"])


def fill_and_submit(values):
    at = open_page(CONFIG["contact"]["file"])
    problems = [f"Page error: {e.value}" for e in at.exception]
    for field in CONFIG["contact_fields"]:
        if field["name"] not in values:
            continue
        kind = {"textarea": "text_area", "select": "selectbox"}.get(field["type"], "text_input")
        try:
            widget = getattr(at, kind)(key=field["name"])
        except Exception:  # noqa: BLE001
            problems.append(f"No st.{kind} with key='{field['name']}' for field '{field['label']}'")
            continue
        try:
            widget.select(values[field["name"]]) if kind == "selectbox" else widget.input(values[field["name"]])
        except Exception as e:  # noqa: BLE001
            problems.append(f"Could not set '{field['name']}' to {values[field['name']]!r}: {e}")
    submit = [b for b in at.button if getattr(b.proto, "is_form_submitter", False)] or list(at.button)
    if not submit:
        return at, problems + ["No form submit button (st.form_submit_button) found on the contact page"]
    submit[0].click().run()
    problems += [f"Error after submit: {e.value}" for e in at.exception]
    return at, problems


def read_rows(csv_file):
    import csv
    return list(csv.reader(csv_file.open(encoding="utf-8"))) if csv_file.exists() else []


def contact():
    csv_file = ROOT / os.environ["CONTACTS_CSV"]
    csv_file.unlink(missing_ok=True)
    fields = CONFIG["contact_fields"]
    good = {f["name"]: sample(f) for f in fields}

    at, problems = fill_and_submit(good)
    rows = read_rows(csv_file)
    if not problems:
        if len(rows) != 2:
            problems.append(f"A valid submission should add 1 row to the CSV, found {max(len(rows) - 1, 0)}")
        elif rows[1][1:] != [good[f["name"]] for f in fields]:
            problems.append(f"CSV row {rows[1][1:]} does not match the submitted values")
        if not at.success:
            problems.append("No st.success thank-you message after a valid submission")
    success = [s.value for s in at.success]

    required = [f for f in fields if f["required"]]
    if required and not problems:
        missing = required[0]["name"]
        at2, more = fill_and_submit({k: v for k, v in good.items() if k != missing})
        problems += more
        if len(read_rows(csv_file)) > len(rows):
            problems.append(f"A submission without the required field '{missing}' was saved to the CSV")
        if not (at2.error or at2.warning):
            problems.append(f"No st.error/st.warning shown when the required field '{missing}' is empty")
    csv_file.unlink(missing_ok=True)
    return {"ok": not problems, "problems": problems, "success_messages": success}


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "render"
    result = render() if mode == "render" else contact()
    print("RESULTS " + json.dumps(result))
'''


def write_scaffold(spec: SiteSpec, theme_id: str, website_dir):
    """Write all fixed files. Agent-written files (layout and pages) are left alone."""
    config = {
        "site_name": spec.site_name,
        "theme": theme_id,
        "pages": [{"name": p.name, "file": p.file, "url_path": p.url_path} for p in spec.pages],
        "contact": {"name": spec.contact.name, "file": spec.contact.file, "url_path": spec.contact.url_path},
        "contact_fields": [f.model_dump() for f in spec.contact.fields],
    }
    files = {
        "app.py": app_py(spec),
        "lib/__init__.py": "",
        "lib/theme.py": theme_py(theme_id),
        "lib/storage.py": STORAGE_PY,
        "components/__init__.py": "",
        "tests/check_site.py": CHECK_SITE_PY,
        ".streamlit/config.toml": config_toml(theme_id),
        "site_config.json": json.dumps(config, indent=2) + "\n",
        "requirements.txt": "streamlit>=1.50\n",
        "data/.gitkeep": "",
        ".gitignore": "__pycache__/\ndata/contacts.test.csv\n",
    }
    website_dir.mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        target = website_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    # Remove page files from an earlier build whose pages are no longer in the spec
    keep = {p.split("/")[-1] for p in allowed_paths(spec) if p.startswith("pages/")}
    for old in (website_dir / "pages").glob("*.py"):
        if old.name not in keep:
            old.unlink()
