"""
Tinitiate AI Academy - Streamlit website entry point.
Generated by scaffold.py. Run it with:  streamlit run app.py
"""
import streamlit as st

from components.layout import render_footer, render_header
from lib.theme import inject_css

st.set_page_config(page_title="Tinitiate AI Academy", page_icon="✨", layout="wide",
                   initial_sidebar_state="collapsed")
inject_css()

PAGES = [
    st.Page("pages/home.py", title="Home", default=True),
    st.Page("pages/courses.py", title="Courses", url_path="courses"),
    st.Page("pages/about_us.py", title="About Us", url_path="about-us"),
    st.Page("pages/contact.py", title="Contact Us", url_path="contact"),
]

page = st.navigation(PAGES, position="hidden")   # navigation is done by the header links
render_header()
page.run()
render_footer()
