"""
Contact form storage: validates a submission and appends it to data/contacts.csv.
Generated by scaffold.py (not by AI) so saving submissions always works.
"""
import csv
import json
import os
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = json.loads((ROOT / "site_config.json").read_text(encoding="utf-8"))
CONTACT_FIELDS = CONFIG["contact_fields"]      # list of {name, label, type, required, options}
EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")


def csv_path() -> Path:
    return ROOT / os.environ.get("CONTACTS_CSV", "data/contacts.csv")


def validate(values: dict) -> str | None:
    """Return an error message, or None if the submission is valid."""
    for field in CONTACT_FIELDS:
        value = str(values.get(field["name"]) or "").strip()
        if field["required"] and not value:
            return f"{field['label']} is required."
        if value and field["type"] == "email" and not EMAIL_RE.match(value):
            return f"{field['label']} is not a valid email address."
        if value and field["type"] == "select" and field["options"] and value not in field["options"]:
            return f"Please choose a valid option for {field['label']}."
    return None


def _cell(value) -> str:
    text = str(value or "").replace("\r", " ").replace("\n", " ").strip()
    return "'" + text if text[:1] in ("=", "+", "-", "@") else text   # block spreadsheet formulas


def save_contact(values: dict) -> str | None:
    """Validate and save one submission. Returns an error message, or None when saved."""
    error = validate(values)
    if error:
        return error
    path = csv_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    is_new = not path.exists()
    with path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        if is_new:
            writer.writerow(["submitted_at"] + [field["name"] for field in CONTACT_FIELDS])
        writer.writerow([datetime.now().isoformat(timespec="seconds")]
                        + [_cell(values.get(field["name"])) for field in CONTACT_FIELDS])
    return None
