"""
Theme "tech-violet" chosen by the Theme Decision Maker agent. Generated by scaffold.py.
Colours are also set in .streamlit/config.toml; this file adds fonts and CSS classes.
"""
import streamlit as st

THEME_ID = "tech-violet"
COLORS = {
    "primary": "#4f46e5",
    "primary-contrast": "#ffffff",
    "secondary": "#7c3aed",
    "accent": "#06b6d4",
    "bg": "#f5f7ff",
    "surface": "#ffffff",
    "text": "#111827",
    "muted": "#4b5563",
    "border": "#e0e7ff",
    "header-bg": "#1e1b4b",
    "header-text": "#ffffff"
}

CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&family=Inter:wght@400;600;700&display=swap');
h1, h2, h3, h4 { font-family: 'Poppins', sans-serif !important; }

/* Header and footer bars: st.container(key="site_header") / st.container(key="site_footer") */
.st-key-site_header, .st-key-site_footer {
    background: #1e1b4b; color: #ffffff;
    padding: 14px 24px; border-radius: 12px;
}
.st-key-site_footer { margin-top: 48px; padding: 28px 24px; }
.st-key-site_header p, .st-key-site_header span, .st-key-site_header a,
.st-key-site_footer p, .st-key-site_footer span, .st-key-site_footer a,
.st-key-site_footer li { color: #ffffff !important; }
/* captions and .muted text must stay readable on the dark bars */
.st-key-site_header [data-testid="stCaptionContainer"], .st-key-site_footer [data-testid="stCaptionContainer"],
.st-key-site_header .muted, .st-key-site_footer .muted { color: #ffffff !important; opacity: 0.8; }
.st-key-site_header .badge, .st-key-site_footer .badge { color: #111827 !important; }
.st-key-site_header a:hover, .st-key-site_footer a:hover { background: rgba(255,255,255,0.12); }

/* Highlighted call-to-action link: st.container(key="header_cta") */
.st-key-header_cta a {
    background: #4f46e5; border-radius: 12px; justify-content: center;
}
.st-key-header_cta a p, .st-key-header_cta a span { color: #ffffff !important; font-weight: 700; }

/* HTML helpers for st.markdown(..., unsafe_allow_html=True) */
.hero {
    background: linear-gradient(135deg, #4f46e5, #7c3aed);
    color: #ffffff; padding: 56px 32px; border-radius: 12px;
    text-align: center; margin-bottom: 24px;
}
.hero h1, .hero h2, .hero p { color: #ffffff !important; }
.card {
    background: #ffffff; border: 1px solid #e0e7ff; border-radius: 12px;
    padding: 20px; height: 100%;
}
.muted { color: #4b5563; }
.badge {
    display: inline-block; padding: 2px 10px; border-radius: 999px;
    background: #e0e7ff; color: #111827; font-size: 0.85rem; margin-right: 6px;
}
</style>
"""


def inject_css():
    st.markdown(CSS, unsafe_allow_html=True)
