"""
Automated site tests (generated by scaffold.py). Uses Streamlit's AppTest to run the app
without a browser.

    python tests/check_site.py render    # render every page, list its links, headings and text
    python tests/check_site.py contact   # fill in and submit the Contact Us form

Prints one line "RESULTS <json>".
"""
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
os.chdir(ROOT)
sys.path.insert(0, str(ROOT))
os.environ.setdefault("CONTACTS_CSV", "data/contacts.test.csv")

from streamlit.testing.v1 import AppTest  # noqa: E402

CONFIG = json.loads((ROOT / "site_config.json").read_text(encoding="utf-8"))
TAG = re.compile(r"<[^>]+>")


def open_page(file=None):
    """Run app.py (header + home page + footer), or with `file` run only that page script."""
    at = AppTest.from_file(str(ROOT / "app.py"), default_timeout=60).run()
    if file:
        at.switch_page(file).run()
    return at


def walk(node):
    yield node
    for child in getattr(node, "children", {}).values():
        yield from walk(child)


def describe(at):
    """Collect headings, text and page links from the rendered page."""
    headings, texts, links = [], [], []
    for el in walk(at.main):
        kind = getattr(el, "type", "")
        if kind in ("title", "header", "subheader"):
            headings.append(el.value)
        elif kind in ("markdown", "caption", "text", "success", "info", "warning", "error"):
            value = str(el.value)
            if "<style>" in value:
                continue
            headings += [TAG.sub("", h).strip() for h in re.findall(r"<h[1-4][^>]*>(.*?)</h[1-4]>", value, re.S)]
            headings += [line.lstrip("# ").strip() for line in value.splitlines() if re.match(r"^#{1,4} ", line)]
            text = re.sub(r"\s+", " ", TAG.sub(" ", value)).strip()
            if text:
                texts.append(text)
        elif kind == "page_link":
            links.append({"label": el.proto.label, "url_path": el.proto.page})
            texts.append(f"[link: {el.proto.label} -> /{el.proto.page}]")
        elif kind == "button":
            texts.append(f"[button: {el.label}]")
        elif kind in ("text_input", "text_area", "selectbox"):
            options = f" options={list(el.options)}" if kind == "selectbox" else ""
            texts.append(f"[form field {kind}: '{el.label}' key={el.key}{options}]")
    return headings, texts, links


def render():
    """Header/footer come from app.py (same on every page); page content from each page file."""
    results = {"layout": None, "pages": []}
    for page in [None] + CONFIG["pages"] + [CONFIG["contact"]]:
        try:
            at = open_page(page and page["file"])
            errors = [str(e.value) for e in at.exception]
            headings, texts, links = describe(at)
            item = {"ok": not errors, "error": "\n".join(errors)[:1500],
                    "headings": headings, "texts": texts, "links": links}
        except Exception as e:  # noqa: BLE001
            item = {"ok": False, "error": f"{type(e).__name__}: {e}"[:1500], "headings": [], "texts": [], "links": []}
        if page is None:
            results["layout"] = item
        else:
            results["pages"].append({"file": page["file"], **item})
    # header/footer text = text of the full app.py run that is not part of the home page itself
    home = results["pages"][0] if results["pages"] else {"texts": [], "links": []}
    results["layout"]["texts"] = [t for t in results["layout"]["texts"] if t not in home["texts"]]
    for link in home["links"]:   # links on the home page itself are not header/footer links
        if link in results["layout"]["links"]:
            results["layout"]["links"].remove(link)
    return results


def sample(field):
    return {"email": "test.user@example.com", "tel": "9876543210",
            "select": field["options"][0] if field["options"] else "Test option",
            "textarea": "Automated test message, with a comma."}.get(field["type"], "Test " + field["label"])


def fill_and_submit(values):
    at = open_page(CONFIG["contact"]["file"])
    problems = [f"Page error: {e.value}" for e in at.exception]
    for field in CONFIG["contact_fields"]:
        if field["name"] not in values:
            continue
        kind = {"textarea": "text_area", "select": "selectbox"}.get(field["type"], "text_input")
        try:
            widget = getattr(at, kind)(key=field["name"])
        except Exception:  # noqa: BLE001
            problems.append(f"No st.{kind} with key='{field['name']}' for field '{field['label']}'")
            continue
        try:
            widget.select(values[field["name"]]) if kind == "selectbox" else widget.input(values[field["name"]])
        except Exception as e:  # noqa: BLE001
            problems.append(f"Could not set '{field['name']}' to {values[field['name']]!r}: {e}")
    submit = [b for b in at.button if getattr(b.proto, "is_form_submitter", False)] or list(at.button)
    if not submit:
        return at, problems + ["No form submit button (st.form_submit_button) found on the contact page"]
    submit[0].click().run()
    problems += [f"Error after submit: {e.value}" for e in at.exception]
    return at, problems


def read_rows(csv_file):
    import csv
    return list(csv.reader(csv_file.open(encoding="utf-8"))) if csv_file.exists() else []


def contact():
    csv_file = ROOT / os.environ["CONTACTS_CSV"]
    csv_file.unlink(missing_ok=True)
    fields = CONFIG["contact_fields"]
    good = {f["name"]: sample(f) for f in fields}

    at, problems = fill_and_submit(good)
    rows = read_rows(csv_file)
    if not problems:
        if len(rows) != 2:
            problems.append(f"A valid submission should add 1 row to the CSV, found {max(len(rows) - 1, 0)}")
        elif rows[1][1:] != [good[f["name"]] for f in fields]:
            problems.append(f"CSV row {rows[1][1:]} does not match the submitted values")
        if not at.success:
            problems.append("No st.success thank-you message after a valid submission")
    success = [s.value for s in at.success]

    required = [f for f in fields if f["required"]]
    if required and not problems:
        missing = required[0]["name"]
        at2, more = fill_and_submit({k: v for k, v in good.items() if k != missing})
        problems += more
        if len(read_rows(csv_file)) > len(rows):
            problems.append(f"A submission without the required field '{missing}' was saved to the CSV")
        if not (at2.error or at2.warning):
            problems.append(f"No st.error/st.warning shown when the required field '{missing}' is empty")
    csv_file.unlink(missing_ok=True)
    return {"ok": not problems, "problems": problems, "success_messages": success}


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "render"
    result = render() if mode == "render" else contact()
    print("RESULTS " + json.dumps(result))
